### ISSUE TITLE
auto-follow

### ISSUE THREAD

**Issue by diemmarkus** [Transkribus/competitions#126]
I have just realized, that people who submit (actively contribute) to a competition are not necessarily in the followers list. Could we add them automatically? -> right now I have to google their names and hope that the e-mail is correct...

**Comment by sfikas** [comment]
Currently it is mandatory for someone to follow a competition in order to be able to submit.
This is the current state for a few weeks now. Before this change, it is true that there were people that submitted that were not necessarily followers.

So, currently the "auto-follow" feature is in effect.
I'll send you details about the users you mention by email.

**Comment by diemmarkus** [comment]
very good - thanks for the contact details!
