### ISSUE TITLE
Open own competition

### ISSUE THREAD

**Issue by gundramleifert** [Transkribus/competitions#18]
I created an account an want to make my on competition - what do I have to do?

**Comment by sfikas** [comment]
I just gave you staff status, so you can login to the administration site.
That'll be xx.site.com/admin instead of the xx.site.com/competitions url you used to login the site.

Click on the 'Add' button next to 'Competitions' to add a competition.
I remind you that there is already a baseline identification competition, you might want to check that first.
Also, you can always clone the repo locally and run django on your own machine if you want full freedom on the site functionality.

**Comment by gundramleifert** [comment]
I have no rights, so far to do anything as admin

**Comment by sfikas** [comment]
After you add the Competition, you have to assign Tracks, Subtracks and Benchmarks on the Competition.

Again, I suggest that you take a look on the two existing competitions first to see how this is done properly.

**Comment by gundramleifert** [comment]
yes, I submitted "BL-results", it worked fine!

**Comment by sfikas** [comment]
cool :)

**Comment by sfikas** [comment]
I just gave you permissions on the admin, i think you can add competitions/tracks etc there too.

**Comment by gundramleifert** [comment]
I set up a competition with track and subtrack - works fine so far. Now I want to add a new error method. As I see, I have to add the executable and define a python-function. But therefore I open a new branch..
