### ISSUE TITLE
Public Links

### ISSUE THREAD

**Issue by diemmarkus** [Transkribus/competitions#98]
Is there a possibility to provide public links (without requiring login) to the datasets?

cheers,
markus

**Comment by sfikas** [comment]
We changed public links to requiring mandatory login. The idea was that this would work to further motivate people to register on Scriptnet. Since registering is a really simple process, adding two kinds of public links - public to everyone and public to registered users, by my point of view would only result in adding unnecessary complexity (just a little more complexity, one could argue, yet still unnecessary) to the platform. @bgatos

**Comment by diemmarkus** [comment]
ok - I have moved the downloads up to the text (since I want to give potential participants the possibility to play with the data before they need any subscription). follow-up question: how do I delete links from existing subtracks?

**Comment by sfikas** [comment]
I'm not sure I understand the question. Did you try deleting the 'public link' using django admin?

**Comment by diemmarkus** [comment]
maybe I am just blind - but I do not find a way to remove the links in the django admin: 
![img-2017-04-11 16 22 22](https://cloud.githubusercontent.com/assets/4182443/24914023/43728562-1ed3-11e7-853b-575e0f073af2.png)

**Comment by sfikas** [comment]
Try going first to django admin 'home', then go to the view of all 
public links, then select it and choose delete.

**Comment by diemmarkus** [comment]
aj - thanks for the hint : )
is it hard to add a delete button where we create links? (I guess there will be a lot of public links in a few years)

**Comment by sfikas** [comment]
Good point! This goes to the todo list :) #100

**Comment by diemmarkus** [comment]
thx!
